export const CategoryFoodTags =
[
    {label: 'Breakfast', value: 'breakfast'},
    {label: 'Lunch', value: 'lunch'},
    {label: 'Brunch', value: 'brunch'},
    {label: 'Quick Snack', value: 'quick_snack '},
    {label: 'Dinner', value: 'dinner'},
    {label: 'Afternoon Snack', value: 'afternoon_snack '},
    {label: 'Late Night Snack', value: 'late_night_snack'},
    {label: 'Before Dinner Snack', value: 'before_dinner_snack'},
    {label: 'Anytime Snack', value: 'anytime_snack'},
    {label: 'Pre-Workout Snack ', value: 'pre_workout_snack '},
    {label: 'After Workout Snack', value: 'after_workout_snack'},
    {label: 'Other', value: 'other'},
    {label: 'Meal Prep', value: 'meal_prep'},
    {label: 'Pasta', value: 'pasta'},
    {label: 'Vegan', value: 'vegan'},
    {label: 'Salad', value: 'salad'},
    {label: 'Appetizer', value: 'appetizer'},
    {label: 'Drinks', value: 'drinks'},
    {label: 'Dessert', value: 'dessert'},
    {label: 'Alcohol', value: 'alcohol'},
    {label: 'Sushi', value: 'sushi'},
    {label: 'Coffee', value: 'coffee'},
];

export const CategoryNonFoodTags =
[
    {label: 'Medicine', value: 'medicine'},
    {label: 'Vitamins', value: 'vitamins'},
    {label: 'Pillow', value: 'pillow'},
    {label: 'Bed', value: 'bed'},
    {label: 'Sleep', value: 'sleep'},
    {label: 'Exercise', value: 'exercise'},
];
export const CategoryRestrauntTags = 
[
    {label: 'Fast Food ', value: 'fast_food '},
    {label: 'Chain Restaurant', value: 'chain_restaurant'},
    {label: 'Italian', value: 'italian'},
    {label: 'Chinese', value: 'chinese'},
    {label: 'Mexican', value: 'mexican'},
    {label: 'American', value: 'american'},
    {label: 'Brunch', value: 'brunch'},
    {label: 'Korea', value: 'korea'},
    {label: 'Pizza', value: 'pizza'},
    {label: 'Japanese', value: 'japanese'},
    {label: 'Seafood', value: 'seafood'},
    {label: 'Thai', value: 'thai'},
    {label: 'French', value: 'french'},
    {label: 'Breakfast', value: 'breakfast'},
    {label: 'Coffee', value: 'coffee'},
    {label: 'Sushi', value: 'sushi'},
    {label: 'Small Plates', value: 'small_plates'},
    {label: 'Barbeque', value: 'barbeque'},
    {label: 'Bakery', value: 'bakery'},
    {label: 'Middle Eastern', value: 'middle_eastern'},
    {label: 'Deli', value: 'deli'},
    {label: 'Asian Fusion ', value: 'asian_fusion'},
];

export const MasterTagList = 
[
    {label: 'Non-Fat', value: 'non&fat'},
    {label: 'For Kids', value: 'for_kids'},
    {label: 'Family Friendly', value: 'family_friendly'},
    {label: 'Low Fat', value: 'low_fat'},
    {label: 'Citrus Feed', value: 'citrus_feed'},
    {label: 'Non-Acidic', value: 'non&acidic'},
    {label: 'Triggering', value: 'triggering'},
    {label: 'High Fat', value: 'high_fat'},
    {label: 'Guilty Pleasure', value: 'guilty_pleasure'},
    {label: 'Low Calorie', value: 'low_calorie'},
    {label: 'Carbonated', value: 'carbonated'},
    {label: 'Low Carb', value: 'low_carb'},
    {label: 'High Carb', value: 'high_carb'},
    {label: 'Watery', value: 'watery'},
    {label: 'Spicy', value: 'spicy'},
    {label: 'sweet', value: 'caffine'},
    {label: 'Tomatoe', value: 'tomatoe'},
    {label: 'Acidic', value: 'acidic'},
    {label: 'Dessert', value: 'dessert'},
    {label: 'Heartburn', value: 'heartburn'},
    {label: 'Indigestion', value: 'indigestion'},
    {label: 'Meat', value: 'meat'},
    {label: 'Chain Resturant', value: 'chain_resturant'},
    {label: 'Vegetarian', value: 'vegetarian'},
    {label: 'Soup', value: 'soup'},
    {label: 'Fatty', value: 'fatty'},
    {label: 'Savory', value: 'savory'},
    {label: 'Seafood', value: 'seafood'},
    {label: 'Cheap', value: 'cheap'},
    {label: 'Easy to Prepare', value: 'easy_to_prepare'},
    {label: 'Expensive', value: 'expensive'},
    {label: 'High Quality', value: 'high_quality'},
    {label: 'Value Meal', value: 'value_meal'},
    {label: 'Affordable', value: 'affordable'},
    {label: 'Go-to meal', value: 'go&to_meal'},
    {label: 'Clean Eating', value: 'clean_eating'},
    {label: 'Pescatarian', value: 'pescatarian'},
    {label: 'Paleo', value: 'paleo'},
    {label: 'Protein', value: 'protein'},
    {label: 'Lean Protien', value: 'lean_protein'},
    {label: 'Salty', value: 'salty'},
    {label: 'Greasy', value: 'greasy'},
    {label: 'Bitter', value: 'bitter'},
    {label: 'Sour', value: 'sour'},
    {label: 'High Vitamins', value: 'high_vitamins'},
    {label: 'High Sodium', value: 'high_sodium'},
    {label: 'Low Sodium', value: 'low_sodium'},
    {label: 'High Fiber', value: 'high_fiber'},
    {label: 'Healthy Fats', value: 'healthy_fats'},
    {label: 'Gum', value: 'gum'},
    {label: 'Eggs', value: 'eggs'},
    {label: 'Pasta', value: 'pasta'},
    {label: 'Gluten', value: 'gluten'},
    {label: 'Gluten Free', value: 'gluten_free'},
    {label: 'Lactose', value: 'lactose'},
    {label: 'Lactose Free', value: 'lactose_free'},
    {label: 'Date Night', value: 'date_night'},
    {label: 'Chicken', value: 'chicken'},
    {label: 'Red Meat', value: 'red_meat'},
    {label: 'Turkey', value: 'turkey'},
    {label: 'Beef', value: 'beef'},
    {label: 'Chinese', value: 'chinese'},
    {label: 'Italian', value: 'italian'},
];